#!/usr/bin/arch -x86_64 zsh

set -euo pipefail

POSITIONAL_ARGS=()

lex_only=false
parse_only=false
codegen_only=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --lex)
      lex_only=true
      shift
      ;;
    ---parse)
      # shellcheck disable=SC2034
      parse_only=true
      shift
      ;;
    --codegen)
      # shellcheck disable=SC2034
      codegen_only=true
      shift
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}"

input_file=$1
input_file_base=${input_file%.*}
preprocessed="$input_file_base".i
compiled="$input_file_base".s
assembled=$input_file_base

gcc -E -P "$input_file" -o "$preprocessed"

cargo run "$preprocessed" -o "$compiled"
lex_ret=$?

if (( lex_ret != 0)); then
  exit $lex_ret
fi

if [ $lex_only = "true" ]; then
  exit 0
fi

gcc "$compiled" -o "$assembled"
rm "$compiled"
